/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.rdfc;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        Rdfc classUnderTest = new Rdfc();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
