/*
 * This source file was generated by the Gradle 'init' task
 */
package rdfc.proc;

import java.util.function.Consumer;

import org.example.IReader;
import org.example.IWriter;
import org.example.Processor;

import com.google.protobuf.ByteString;

/**
 * TestProcessor
 */
public class Library extends Processor<Library.Args> {

    public Library(Args args) {
        super(args);
    }

    public void init(Consumer<Void> callback) {
        callback.accept(null);
    }

    public void transform(Consumer<Void> callback) {
        this.arguments.reader.buffers().on(st -> st.ifPresentOrElse(msg -> {
            System.out.println("Got string " + msg.toStringUtf8());
        }, () -> {
        }));

    }

    public void produce(Consumer<Void> callback) {
        System.out.println("Producing");
        this.arguments.writer.msg(ByteString.copyFromUtf8("Hallo " + this.arguments.name));
    }

    public static class Args {
        public String name;
        public IReader reader;
        public IWriter writer;
    }
}
